[package]
name = "painting_tracker"
version = "0.1.0"
authors = ["Grant Merola <grantmerola@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

diesel = { version = "1.4.2", features = ["mysql"] }